version: '3.8'

services:
  metabase:
    image: metabase:latest
    platform: linux/arm64
    container_name: metabase
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - MB_DB_FILE=/metabase-data/metabase.db
      # Configurações de timezone
      - JAVA_TIMEZONE=America/La_Paz
      # Configurações de memória Java
      - JAVA_OPTS=-XX:+ExitOnOutOfMemoryError -Xmx2g -Xms512m
      # Configurações opcionais (descomente se necessário)
      #- MB_PASSWORD_COMPLEXITY=strong
      #- MB_PASSWORD_LENGTH=10
      #- MB_ENCRYPTION_SECRET_KEY=sua_chave_secreta
    volumes:
      - metabase-data:/metabase-data
      - ./plugins:/plugins
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 40s

volumes:
  metabase-data:
    driver: local
